ecommerce/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls')),
    path('store/', include('store1.urls')),
    path('math/', include('maths.urls')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

maths/urls.py
from django.urls import path
from . import views 


app_name = 'math'

urlpatterns = [
    path('', views.index, name='index')
]

store/urls.py
from django.urls import path
from . import views
urlpatterns = [

    path('', views.index, name='index'),
    path('cart/', views.cart, name='cart'),
    path('checkout/', views.checkout, name='checkout'),
    path('update_item/', views.updateItem, name='update_item'),

]

store1/urls.py
from django.urls import path
from . import views

app_name = 'store1'

urlpatterns = [

    path('', views.index, name='store'),
    path('cart/', views.cart, name='cart'),
    path('checkout/', views.checkout, name='checkout'),
]

maths/models.py
from django.db import models

# Create your models here.


class Math_type(models.Model):

    sign = models.CharField(max_length=50)

    def __str__(self):
        return self.sign


class Math(models.Model):

    number1 = models.FloatField(default=0)
    number2 = models.FloatField(default=0)
    add_sign = models.OneToOneField(
        Math_type,  on_delete=models.SET_NULL, null=True)

    def get_total(self):

        if '+' == self.add_sign.sign:  # self.add_sign to Math_type app's sign

            total = self.number1+self.number2
            return total

        elif '-' == self.add_sign.sign:  # self.add_sign to Math_type app's sign

            total = self.number1-self.number2
            return total

        elif '*' == self.add_sign.sign:  # self.add_sign to Math_type app's sign

            total = self.number1*self.number2
            return total

        elif '/' == self.add_sign.sign:  # self.add_sign to Math_type app's sign

            total = self.number1/self.number2
            return total

store/models.py
from django.db import models
from django.contrib.auth.models import User
import random
# Create your models here.


class Customer(models.Model):

    user = models.OneToOneField(
        User, on_delete=models.CASCADE, null=True, blank=True)
    name = models.CharField(max_length=40, null=True)
    email = models.CharField(max_length=200)

    def __str__(self):
        return str(self.user)


class Product(models.Model):

    name = models.CharField(max_length=100)
    price = models.FloatField()
    product_image = models.ImageField(null=True, blank=True)
    digital = models.BooleanField(default=False, null=True, blank=True)


    def __str__(self):
        return self.name

# if u dont upload a image, then u dont hava to face error this code help u
    @property
    def imageURL(self):
        try:
            url = self.product_image.url
        except:
            url = ''
        return url


class Order(models.Model):

    customer = models.ForeignKey(
        Customer, on_delete=models.SET_NULL, null=True, blank=True)
    order_date = models.DateTimeField(auto_now_add=True)
    complete = models.BooleanField(default=False)
    transaction_id = models.CharField(max_length=100, blank=True)

    def __str__(self):
        return str(self.id)

    @property
    def get_cart_total(self):
        # chid class is inherited here with "self.orderitem_set.all()"
        orderitems = self.orderitem_set.all()

        # sum function can work with tuple and list. Here it is a list
        all = [item.get_total for item in orderitems]

        total = sum(all)
        return total

    @property
    def get_cart_Item_total(self):
        orderitems = self.orderitem_set.all()
        all = [item.quantity for item in orderitems]
        total = sum(all)

        return total
    
    @property

    def shipping(self):

        shipping = False

        orderitems = self.orderitem_set.all()

        for i in orderitems:
            if i.product.digital == False:
                shipping = True
        return shipping



# this is to generate transaction id with random module
    def save(self, *args, **kwargs):
        number_list = [x for x in range(10)]
        code_items = []
        for i in range(10):
            num = random.choice(number_list)
            code_items.append(num)
        code_string = "".join(str(item) for item in code_items)
        self.transaction_id = code_string
        super().save(*args, **kwargs)


class OrderItem(models.Model):

    product = models.ForeignKey(
        Product, on_delete=models.SET_NULL, null=True)
    order = models.ForeignKey(Order, on_delete=models.SET_NULL, null=True)
    quantity = models.IntegerField(default=0, null=True, blank=True)
    date_added = models.DateTimeField(auto_now_add=True)


# to find total price

    @property
    def get_total(self):
        total = self.product.price * self.quantity
        return total


class ShippingAddress(models.Model):

    customer = models.ForeignKey(
        Customer, on_delete=models.SET_NULL, null=True)
    order = models.ForeignKey(
        Order, on_delete=models.SET_NULL, null=True)
    address = models.CharField(max_length=200, null=False)
    city = models.CharField(max_length=200, null=False)
    state = models.CharField(max_length=200, null=False)
    city = models.CharField(max_length=200, null=False)
    zip_code = models.CharField(max_length=200, null=False)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.address

store1/models.py
from django.db import models
from django.contrib.auth.models import User
import random
# Create your models here.


class Customer1(models.Model):

    user = models.OneToOneField(
        User, on_delete=models.CASCADE, null=True, blank=True)
    full_name = models.CharField(max_length=50)
    email = models.CharField(max_length=200, null=True, blank=True)

    def __str__(self):
        return str(self.user)


class Product1(models.Model):

    name = models.CharField(max_length=200)
    price = models.FloatField()
    added_date = models.DateTimeField(auto_now_add=True)
    product_image = models.ImageField()
    digital = models.BooleanField(default=False)

    def __str__(self):
        return self.name

    @property
    def imageURL(self):

        try:
            url = self.product_image.url
        except:
            url = ''

        return url


class Order1(models.Model):

    customer = models.ForeignKey(
        Customer1,  on_delete=models.SET_NULL, null=True, blank=True)
    order_date = models.DateTimeField(auto_now_add=True)
    transaction_id = models.CharField(max_length=30,  null=True, blank=True)
    complete = models.BooleanField(default=False, null=True, blank=True)

    def __str__(self):
        return str(self.id)

    # this is to generate transaction id with random module
    def save(self, *args, **kwargs):
        number_list = [x for x in range(10)]
        code_items = []
        for i in range(10):
            num = random.choice(number_list)
            code_items.append(num)
        code_string = "".join(str(item) for item in code_items)
        self.transaction_id = code_string
        super().save(*args, **kwargs)

    def total_amount(self):
        orderitems = self.orderitem1_set.all()

        orders = [item.get_total for item in orderitems]

        all = sum(orders)

        return all

    def total_items(self):
        orderitems = self.orderitem1_set.all()

        orders = [item.quantity for item in orderitems]

        all = sum(orders)

        return all


class OrderItem1(models.Model):

    product = models.ForeignKey(
        Product1,  on_delete=models.SET_NULL, null=True)
    order = models.ForeignKey(Order1,  on_delete=models.SET_NULL, null=True)
    date = models.DateTimeField(auto_now_add=True)
    quantity = models.IntegerField(default=0)

    @property
    def get_total(self):

        all = self.quantity * self.product.price

        return all

maths/forms.py
from .models import Math
from django.forms import ModelForm


class MathForm(ModelForm):

    class Meta:
        model = Math
        fields = '__all__'

maths/views.py
from django.shortcuts import render
from . models import *
from . forms import MathForm

# Create your views here.


def index(request):
    template = 'maths.html'

    if request.method == 'POST':

       math = Math.objects.get(id=1)

       form = MathForm(request.POST, instance=math)

       form.save()

    else:
        math = Math.objects.get(id=1)

        form = MathForm(instance=math)

    context = {

        'math': math,
        'form': form,

    }

    return render(request, template_name=template, context=context)

store/views.py
from django.shortcuts import render
from . models import *
# Create your views here.
from django.http import JsonResponse
import json

def index(request):
    template = 'store.html'
    product = Product.objects.all()
    

    context = {
        'products': product,

    }

    return render(request, template_name=template, context=context)


def cart(request):
    template = 'cart.html'
    if request.user.is_authenticated:
        customer = request.user.customer  # user app to customer app by one to one relation

        order, created = Order.objects.get_or_create(
            customer=customer, complete=False)
        cartitem = order.get_cart_Item_total

        items = order.orderitem_set.all()  # it will return exact user's order item
        # items = OrderItem.objects.all() # it will return all user's order item
    else:
        items = []
        # when user not authenticated it works
        order = {'get_cart_Item_total': 0, 'get_cart_total': 0, 'shipping': False}

        cartitem = order['get_cart_Item_total']

    context = {
        'items': items,
        'order': order,
        'cartitem': cartitem,
    }

    return render(request, template_name=template, context=context)



def checkout(request):
    template = 'checkout.html'
    if request.user.is_authenticated:
        customer = request.user.customer  # user app to customer app by one to one relation

        order, created = Order.objects.get_or_create(
            customer=customer, complete=False)

        items = order.orderitem_set.all()  # it will return exact user's order item
        # items = OrderItem.objects.all() # it will return all user's order item
    else:
        items = []
        # when user not authenticated it works
        order = {'get_cart_Item_total': 0, 'get_cart_total': 0, 'shipping': False}

    context = {
        'items': items,
        'order': order,
    }

    return render(request, template_name=template, context=context)

def updateItem(request):

    data = json.loads(request.body)
    productId = data['productId']
    action = data['action']


    customer = request.user.customer

    product = Product.objects.get(id=productId)
    order, created = Order.objects.get_or_create(
            customer=customer, complete=False)
    
    orderitem, created = OrderItem.objects.get_or_create(order = order, product = product)
    print('before if',orderitem.quantity)
    if action == 'add':

        orderitem.quantity = orderitem.quantity + 1

    elif action == 'remove':

        orderitem.quantity = orderitem.quantity - 1

    orderitem.save()

    if orderitem.quantity <= 0:

        orderitem.delete()

      
    

    return JsonResponse('Item was added', safe=False)

store1/views.py
from django.shortcuts import render
from . models import *
# Create your views here.


def index(request):

    template = 'store1.html'

    products = Product1.objects.all()

    context = {
        'products': products
    }
    return render(request, template_name=template, context=context)


def cart(request):

    template = 'cart1.html'

    if request.user.is_authenticated:

        # user app to customer1 app by one to one relation
        customer = request.user.customer1

        order, created = Order1.objects.get_or_create(
            customer=customer, complete=False)

        items = order.orderitem1_set.all()

    context = {
        'order': order,
        'items': items,

    }
    return render(request, template_name=template, context=context)


def checkout(request):

    template = 'checkout1.html'

    context = {

    }
    return render(request, template_name=template, context=context)

templates/cart.html
{% extends 'main.html' %}
{% load static %}
{% block title %}Cart{% endblock title %}

{% block content %}








	<div class="row">
		<div class="col-lg-12">
			<div class="box-element">

				<a  class="btn btn-outline-dark" href="#">&#x2190; Continue Shopping</a>

				<br>
				<br>
				<table class="table">
					<tr>
						<th><h5>Items: <strong>{{order.get_cart_Item_total}}</strong></h5></th>
						<th><h5>Total:<strong> ${{order.get_cart_total}}</strong></h5></th>
						<th>
							<a  style="float:right; margin:5px;" class="btn btn-success" href="{% url 'checkout' %}">Checkout</a>
						</th>
					</tr>
				</table>

			</div>

			<br>
			<div class="box-element">
				<div class="cart-row">
					<div style="flex:2"></div>
					<div style="flex:2"><strong>Item</strong></div>
					<div style="flex:1"><strong>Price</strong></div>
					<div style="flex:1"><strong>Quantity</strong></div>
					<div style="flex:1"><strong>Total</strong></div>
				</div>
				


			{% for item in items %}
				<div class="cart-row">
					<div style="flex:2"><img class="row-image" src="{{item.product.imageURL}}"></div>
					<div style="flex:2"><p>{{item.product.name}}</p></div>
					<div style="flex:1"><p>${{item.product.price}}</p></div>
					<div style="flex:1">
						<p class="quantity">{{item.quantity}}</p>
						<div class="quantity">
							<img data-product={{item.product.id}} data-action="add" class="chg-quantity update-cart" src="{% static  'images/up.jpg' %}">
							
							<img data-product={{item.product.id}} data-action = "remove" class="chg-quantity update-cart" src="{% static  'images/down.png' %}">
						</div>
					</div>
					<div style="flex:1"><p>${{item.get_total}}</p></div>
				</div>
			{% endfor %}


			</div>
		</div>
	</div>








{% endblock content %}

templates/cart1.html
{% extends 'main.html' %}
{% load static %}
{% block title %}Cart{% endblock title %}

{% block content %}





	<div class="row">
		<div class="col-lg-12">
			<div class="box-element">

				<a  class="btn btn-outline-dark" href="#">&#x2190; Continue Shopping</a>

				<br>
				<br>
				<table class="table">
					<tr>
						<th><h5>Items: <strong>{{order.total_items}}</strong></h5></th>
						<th><h5>Total:<strong> ${{order.total_amount}}</strong></h5></th>
						<th>
							<a  style="float:right; margin:5px;" class="btn btn-success" href="{% url 'store1:checkout' %}">Checkout</a>
						</th>
					</tr>
				</table>

			</div>

			<br>
			<div class="box-element">
				<div class="cart-row">
					<div style="flex:2"></div>
					<div style="flex:2"><strong>Item</strong></div>
					<div style="flex:1"><strong>Price</strong></div>
					<div style="flex:1"><strong>Quantity</strong></div>
					<div style="flex:1"><strong>Total</strong></div>
				</div>
				

                  {% for item in items %}
		          		<div class="cart-row">
		          			<div style="flex:2"><img class="row-image" src="{{item.product.imageURL}}"></div>
		          			<div style="flex:2"><p>{{item.product.name}}</p></div>
		          			<div style="flex:1"><p>${{item.product.price}}</p></div>
		          			<div style="flex:1">
		          				<p class="quantity">{{item.quantity}}</p>
		          				<div class="quantity">
		          					<img class="chg-quantity" src="{% static  'images/up.jpg' %}">
		          			
		          					<img class="chg-quantity" src="{% static  'images/down.png' %}">
		          				</div>
		          			</div>
		          			<div style="flex:1"><p>${{item.get_total}}</p></div>
		          		</div>
		          {% endfor %}
          
          
		    </div>
		</div>
	</div>








{% endblock content %}

templates/checkout.html
{% extends 'main.html' %}

{% load static %}

{% block title %}Checkout{% endblock title %}

{% block content %}

 <div class="row">
		<div class="col-lg-6">
			<div class="box-element" id="form-wrapper">
				<form id="form">
					<div id="user-info">
						<div class="form-field">
							<input required class="form-control" type="text" name="name" placeholder="Name..">
						</div>
						<div class="form-field">
							<input required class="form-control" type="email" name="email" placeholder="Email..">
						</div>
					</div>
					
					<div id="shipping-info">
						<hr>
						<p>Shipping Information:</p>
						<hr>
						<div class="form-field">
							<input class="form-control" type="text" name="address" placeholder="Address..">
						</div>
						<div class="form-field">
							<input class="form-control" type="text" name="city" placeholder="City..">
						</div>
						<div class="form-field">
							<input class="form-control" type="text" name="state" placeholder="State..">
						</div>
						<div class="form-field">
							<input class="form-control" type="text" name="zipcode" placeholder="Zip code..">
						</div>
						<div class="form-field">
							<input class="form-control" type="text" name="country" placeholder="Zip code..">
						</div>
					</div>

					<hr>
					<input id="form-button" class="btn btn-success btn-block" type="submit" value="Continue">
				</form>
			</div>

			<br>
			<div class="box-element hidden" id="payment-info">
				<small>Paypal Options</small>
			</div>
			
		</div>

		<div class="col-lg-6">
			<div class="box-element">
				<a class="btn btn-outline-dark" href="{% url 'cart' %}">&#x2190; Back to Cart</a>
				<hr>
				<h3>Order Summary</h3>
				<hr>
				{% for item in items %}
				<div class="cart-row">
					<div style="flex:2"><img class="row-image" src="{{item.product.imageURL}}"></div>
					<div style="flex:2"><p>{{item.product.name}}</p></div>
					<div style="flex:1"><p>${{item.product.price}}</p></div>
					<div style="flex:1"><p>x{{item.quantity}}</p></div>
				</div>
				{% endfor %}
				<h5>Items:   {{order.get_cart_Item_total}}</h5>
				<h5>Total:   ${{order.get_cart_total}}</h5>
			</div>
		</div>
	</div>



<script type="text/javascript">
   
   var shipping = '{{order.shipping}}'
   if (shipping == 'False'){

	   document.getElementById('shipping-info').innerHTML = ''
   }

</script>


{% endblock content %}

templates/checkout1.html
{% extends 'main.html' %}
{% load static %}

{% block title %}Checkout{% endblock title %}

{% block content %}


 <div class="row">
		<div class="col-lg-6">
			<div class="box-element" id="form-wrapper">
				<form id="form">
					<div id="user-info">
						<div class="form-field">
							<input required class="form-control" type="text" name="name" placeholder="Name..">
						</div>
						<div class="form-field">
							<input required class="form-control" type="email" name="email" placeholder="Email..">
						</div>
					</div>
					
					<div id="shipping-info">
						<hr>
						<p>Shipping Information:</p>
						<hr>
						<div class="form-field">
							<input class="form-control" type="text" name="address" placeholder="Address..">
						</div>
						<div class="form-field">
							<input class="form-control" type="text" name="city" placeholder="City..">
						</div>
						<div class="form-field">
							<input class="form-control" type="text" name="state" placeholder="State..">
						</div>
						<div class="form-field">
							<input class="form-control" type="text" name="zipcode" placeholder="Zip code..">
						</div>
						<div class="form-field">
							<input class="form-control" type="text" name="country" placeholder="Zip code..">
						</div>
					</div>

					<hr>
					<input id="form-button" class="btn btn-success btn-block" type="submit" value="Continue">
				</form>
			</div>

			<br>
			<div class="box-element hidden" id="payment-info">
				<small>Paypal Options</small>
			</div>
			
		</div>

		<div class="col-lg-6">
			<div class="box-element">
				<a  class="btn btn-outline-dark" href="{% url 'store1:cart' %}">&#x2190; Back to Cart</a>
				<hr>
				<h3>Order Summary</h3>
				<hr>
				<div class="cart-row">
					<div style="flex:2"><img class="row-image" src="{% static 'images/product.jpg' %}"></div>
					<div style="flex:2"><p>Product 1</p></div>
					<div style="flex:1"><p>$20.00</p></div>
					<div style="flex:1"><p>x2</p></div>
				</div>
				<h5>Items:   </h5>
				<h5>Total:   $4</h5>
			</div>
		</div>
	</div>






{% endblock content %}

templates/main.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">


    <script type="text/javascript">

        var user = '{{request.user}}'

            function getToken(name) {
                let cookieValue = null;
                if (document.cookie && document.cookie !== '') {
                    const cookies = document.cookie.split(';');
                    for (let i = 0; i < cookies.length; i++) {
                        const cookie = cookies[i].trim();
                        // Does this cookie string begin with the name we want?
                        if (cookie.substring(0, name.length + 1) === (name + '=')) {
                            cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                            break;
                        }
                    }
                }
                return cookieValue;
            }
            const csrftoken = getToken('csrftoken');

    </script>
    
    <title>Titash Store | {% block title %}{% endblock title %}</title>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="{% url 'index' %}">Titash Store</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="#">Store</a>
      </li>

    </ul>

    	    <div  class="form-inline my-2 my-lg-0">
	     	<a href="#"class="btn btn-warning">Login</a>
	     	
	     	<a href="{% url 'cart' %}">
	    		<img  id="cart-icon" src="{% static 'images/cart.jpg' %}">
	    	</a>
	    	<p id="cart-total">{{cartitem}}</p>

	    </div>
  </div>
</nav>
<br>
<br>
<br>
    <div class="container">
    {% block content %}{% endblock content %}
    </div>
 <script src="{% static 'bootstrap/css/bootstrap.min.js' %}"></script>
 <script src="{% static 'js/cart.js' %}"></script>
</body>
</html>

templates/maths.html
{% extends 'main.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block title %}Math{% endblock title %}

{% block content %}

<form  method='POST' action="">
   {% csrf_token %}
   {{form|crispy}}
   <br>
   <input class="btn btn-success" type="submit" value="Result">
</form>
<hr>

<h1>Result: {{math.number1}} {{math.add_sign}} {{math.number2}} = {{math.get_total}}</h1>


{% endblock content %}

templates/store.html
{% extends 'main.html' %}
{% load static %}
{% block title %}Home{% endblock title %}

{% block content %}

<a href="{% url 'store1:store' %}">Store1</a>
<hr>
<a href="{% url 'math:index' %}">Math</a>
<div class="row"> 

 
 {% for product in products %}
  <div class="col-lg-4 my-4">

    <div class="card" style="width: 18rem;">
   
      <img class="thumbnail" src="{{product.imageURL}}" alt="Card image cap">
   
      <div class="card-body">
        <h5 class="card-title">{{product.name}}</h5>
        <hr>
      
        <button data-product = {{product.id}} data-action="add"  class="btn btn-outline-secondary update-cart">Add to cart</button>
        <a href="#" class="btn btn-outline-success">view</a>
        <h5 style="float: right;" class="d-inline-block"> {{product.price}}$</h5>  
      </div>
    </div>
  </div>
 
{% endfor %}
  
</div> 






{% endblock content %}

templates/store1.html
{% extends 'main.html' %}

{% block title %}Store1{% endblock title %}

{% block content %}


<div class="row"> 
  {% for product in products %}
  <div class="col-lg-4 my-4">
    <div class="card" style="width: 18rem;">
   
      <img class="thumbnail" src="{{product.imageURL}}" alt="Card image cap">
   
      <div class="card-body">
        <h5 class="card-title">{{product.name}}</h5>
        <hr>
      
        <a href="{% url 'store1:cart' %}" class="btn btn-outline-secondary">Add to cart</a>
        <a href="#" class="btn btn-outline-success">view</a>
        <h5 style="float: right;" class="d-inline-block"> {{product.price}}$</h5>  
      </div>
    </div>
  </div>
  {% endfor %}
 
</div> 


{% endblock content %}